### ISSUE TITLE
wigle error

### ISSUE THREAD

**Issue by edlovesiraq** [VBQL/AWSY#5]
Hello.,
Huge fan of the idea but can't get it to work. I've double checked this SSID, and know there is only one in the wigle.net db. I can find it by searching the web site but when I do it via AWSY i get the bellow error. Any help is appreciated. 

```
[12:14:58] root@android:~/AWSY# python AWSY.py 4C17eb7ca35f
Visit https://wigle.net/account to collect your API token
Then add your credentials to /usr/local/lib/python2.7/dist-packages/pygle/config.pyc
('Searching WiGLE.net:', '4C:17:eb:7c:a3:5f')
4C:17:eb:7c:a3:5f
{u'error': {u'message': u'Not Found', u'code': 404, u'errors': [{u'reason': u'notFound', u'message': u'Not Found', u'domain': u'geolocation'}]}}
Traceback (most recent call last):
  File "AWSY.py", line 41, in <module>
    run(sys.argv[1])
  File "AWSY.py", line 15, in run
    (loc_x, loc_y) = googleAPI.get_coordinates(bssid)
  File "/root/AWSY/Locator.py", line 71, in get_coordinates
    return results["location"]["lat"], results["location"]["lng"]
KeyError: 'location'

```

Love this idea! any help is appreciated.

**Comment by edlovesiraq** [comment]
Follow up:
So I tried again on a known and owned BSSID that only comes to
